import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ValueNotifier<Locale> {
  static final LanguageService instance = LanguageService._();

  LanguageService._() : super(const Locale('fr'));

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('language') ?? 'fr';
    value = Locale(langCode);
  }

  Future<void> setLanguage(String langCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', langCode);
    value = Locale(langCode);
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      // General
      'app_title': 'Militant',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'error': 'Erreur',
      'loading': 'Chargement...',
      'success': 'Succès',
      'confirm': 'Confirmer',
      'delete': 'Supprimer',
      'report': 'Signaler',
      'share': 'Partager',
      'edit': 'Modifier',
      'close': 'Fermer',
      'settings_updated': 'Réglages mis à jour',

      // Auth
      'login_title': 'Connexion',
      'email_label': 'Email',
      'password_label': 'Mot de passe',
      'login_button': 'Se connecter',
      'register_link': 'Pas encore de compte ? S\'inscrire',
      'register_title': 'Inscription',
      'create_account': 'Créer un compte',
      'join_community': 'Rejoignez la communauté militante',
      'username_label': 'Nom d\'utilisateur',
      'register_button': 'S\'inscrire',
      'login_link': 'Déjà un compte ? Se connecter',
      'password_required': 'Mot de passe requis',
      'email_required': 'Email requis',
      'confirm_password': 'Confirmer le mot de passe',
      'your_main_cause': 'Ta cause principale',
      'choose_cause': 'Choisir une cause',

      // Home & Navigation
      'home_title': 'Accueil',
      'messages_title': 'Chat',
      'profile_title': 'Profil',
      'settings_title': 'Réglages',
      'groups_title': 'Groupes',
      'events_title': 'Événements',
      'pages_title': 'Pages',
      'notifications_title': 'Notifs',
      'test_notifications': 'Tester les notifications',
      'test_notifications_desc': 'Envoyer une notification de test maintenant',
      'notification_test_sent': 'Test envoyé ! Vérifiez vos notifications.',
      'friends_title': 'Amis',
      'friend_requests': 'Demandes',
      'accept': 'Accepter',
      'decline': 'Refuser',
      'search_hint': 'Rechercher...',
      'discover': 'Découvrir',
      'community_tab_title': 'Communauté',
      'explore_mobilize_title': 'Explorez et Mobilisez-vous',
      'groups_desc': 'Rejoignez la lutte locale et organisez-vous.',
      'events_desc': 'Manifestations, assemblées et actions.',
      'pages_desc': 'Suivez les collectifs et organisations.',
      'moderation_desc': 'Gérez les signalements et la sécurité.',
      'feed_tab_discover': 'Découvrir',
      'feed_tab_following': 'Abonnements',
      'empty_feed_following':
          "Aucun post dans vos abonnements.\nAbonnez-vous ou allez dans 'Découvrir' !",
      'empty_feed_global': 'Aucun post disponible pour le moment.',

      // Posts
      'create_post_title': 'Nouveau post',
      'create_post_hint': 'Quoi de neuf ?',
      'publish_button': 'Publier',
      'post_detail_title': 'Post',
      'comments_title': 'Commentaires',
      'comment_hint': 'Ajouter un commentaire...',
      'like_action': 'J\'aime',
      'comment_action': 'Commenter',
      'share_action': 'Partager',
      'delete_post_confirm': 'Voulez-vous vraiment supprimer ce post ?',
      'report_post_title': 'Signaler le post',
      'report_reason_hint': 'Raison du signalement',
      'report_submit': 'Envoyer',

      // Profile
      'edit_profile_title': 'Modifier le profil',
      'edit_profile_subtitle': 'Bio, site web et réseaux sociaux',
      'profile_info_title': 'Informations du profil',
      'bio_label': 'Biographie',
      'bio_hint': 'Parlez de vous...',
      'website_label': 'Site web',
      'location_label': 'Localisation',
      'location_hint': 'Ville, Pays',
      'social_links_title': 'Réseaux sociaux',
      'save_button': 'Enregistrer',
      'saved_posts_title': 'Posts sauvegardés',
      'posts': 'Posts',
      'media': 'Médias',
      'followers': 'Abonnés',
      'following': 'Abonnements',
      'no_posts': 'Aucun post',
      'no_media': 'Aucun média',
      'logout': 'Déconnexion',

      // Settings
      'security_title': 'Sécurité',
      'privacy_title': 'Confidentialité',
      'language_title': 'Langue',
      'theme_title': 'Thème',
      'about_title': 'À propos',
      'theme_dark': 'Sombre',
      'theme_light': 'Clair',
      'choose_language': 'Choisir la langue',
      'choose_theme': 'Choisir le thème',
      'subtitle_notifications': 'Gérer les notifications',
      'subtitle_security': 'Changer de mot de passe',
      'subtitle_privacy': 'Paramètres de confidentialité',
      'version': 'Version 1.0.5',

      // Notifications Settings
      'notifications_push': 'Notifications push',
      'notifications_push_subtitle': 'Sur cet appareil',
      'notifications_email': 'E-mails',
      'notifications_email_subtitle': 'Recevoir des résumés par mail',
      'notifications_likes': 'J\'aime',
      'notifications_likes_subtitle': 'Quand quelqu\'un aime vos posts',
      'notifications_comments': 'Commentaires',
      'notifications_comments_subtitle': 'Quand quelqu\'un commente',
      'notifications_messages': 'Messages prives et groupes',
      'notifications_messages_subtitle':
          'Nouveaux messages prives et messages de groupes',
      'notifications_friend_requests': 'Demandes d\'amis',
      'notifications_friend_requests_subtitle':
          'Nouvelles demandes d\'amis et acceptations',
      'notifications_follows': 'Abonnements',
      'notifications_follows_subtitle': 'Nouveaux abonnés',
      'notifications_mentions': 'Mentions',
      'notifications_mentions_subtitle': 'Quand on vous mentionne',
      'notifications_channels_title': 'CANAUX',
      'notifications_interactions_title': 'INTERACTIONS',

      // Privacy Settings
      'privacy_private_account': 'Compte privé',
      'privacy_private_subtitle':
          'Seuls vos abonnés peuvent voir vos posts et médias',
      'privacy_allow_messages': 'Messages privés',
      'privacy_allow_messages_subtitle':
          'Autoriser tout le monde à vous envoyer des messages',
      'privacy_online_status': 'Statut en ligne',
      'privacy_online_subtitle': 'Afficher quand vous êtes actif',
      'privacy_read_receipts': 'Confirmations de lecture',
      'privacy_read_receipts_subtitle': 'Voir quand vos messages sont lus',

      // Change Password
      'change_password_title': 'Changer de mot de passe',
      'current_password': 'Mot de passe actuel',
      'new_password': 'Nouveau mot de passe',
      'password_match_error': 'Les mots de passe ne correspondent pas',
      'password_min_length': 'Minimum 8 caractères',
      'update_button': 'Mettre à jour',
      'password_updated': 'Mot de passe modifié avec succès',

      // Chat
      'message_hint': 'Message...',
      'message_group_hint': 'Message au groupe...',
      'online': 'En ligne',
      'private_account_title': 'Ce compte est privé',
      'private_account_subtitle': 'Abonnez-vous pour voir ses publications.',
      'no_messages': 'Aucun message',
      'no_group_messages': 'Aucun message dans ce groupe',
      'no_conversations': 'Aucune conversation',
      'no_group_discussions': 'Aucun groupe de discussion',
      'user': 'Utilisateur',
      'anonymous_user': 'Anonyme',
      'me_label': 'Moi',
      'gallery': 'Galerie',
      'camera': 'Appareil photo',
      'delete_question': 'Supprimer ?',
      'delete_message_confirm': 'Voulez-vous supprimer ce message ?',
      'delete_conversation_confirm':
          'Voulez-vous supprimer toute cette conversation ? Cette action est définitive.',
      'conversation_deleted': 'Conversation supprimée',
      'edit_message': 'Modifier le message',
      'translate_action': 'Traduire',
      'original_label': 'Original',
      'edited_label': 'Modifié',
      'ephemeral_minutes': 'Éphémère : {minutes} min',
      'follow': 'Suivre',
      'following_status': 'Suivi',
      'add_friend': 'Ajouter un ami',
      'friend_request_sent': 'Demande envoyée',
      'friend_request_received': 'Demande d\'ami reçue',
      'message': 'Message',
      'friends': 'Amis',
      'error_generic': 'Erreur',
      'cannot_open_url': 'Impossible d\'ouvrir',

      // Stories
      'stories_add': 'Ajouter',
      'stories_created': 'Story créée',
      'stories_error': 'Erreur',
      'stories_title': 'Stories',

      // Badge Selection
      'my_militant_badge': 'Badge militant',
      'no_badge': 'Aucun badge',
      'select_badge_text': 'Choisir affiliation',
      'export_data_title': 'Exporter données',
      'export_data_subtitle': 'Copie JSON',
      'two_factor_title': 'Authentification (2FA)',
      'two_factor_subtitle': 'Code TOTP',
      'delete_account_title': 'Supprimer mon compte',
      'delete_account_subtitle': 'Demander la suppression définitive',
      'delete_account_confirm': 'Supprimer définitivement',
      'delete_account_warning':
          'Attention : Cette action est irréversible. Toutes vos données seront effacées. Un e-mail de confirmation vous sera envoyé.',
      'enter_password_to_delete': 'Entrez votre mot de passe pour confirmer',
      'delete_account_request_sent':
          'Demande envoyée ! Vérifiez vos e-mails pour confirmer.',

      // Moderation
      'mod_title': 'Modération',
      'mod_tab_reports': 'Signalements',
      'mod_tab_candidates': 'Candidats',
      'mod_tab_moderators': 'Modérateurs',
      'mod_tab_sanctions': 'Sanctions',
      'mod_principles_title': 'Principes de modération',
      'mod_principles_text':
          '• Égalité totale\n• Pas de hiérarchie\n• Décisions par consensus (70%)\n• Tout le monde peut voter\n• Modérateurs révocables',
      'mod_apply_btn': 'Se porter candidat·e',
      'mod_apply_dialog_title': 'Se porter candidat·e',
      'mod_apply_dialog_desc':
          'Explique pourquoi tu souhaites devenir modérateur·ice :',
      'mod_apply_hint': 'Ta motivation...',
      'mod_apply_send': 'Envoyer',
      'mod_apply_cancel': 'Annuler',
      'mod_apply_success': 'Candidature envoyée !',
      'mod_vote_remove': 'Supprimer',
      'mod_vote_warn': 'Avertir',
      'mod_vote_keep': 'Garder',
      'mod_action_direct_delete': 'Suppr. directe',
      'mod_action_warn': 'Avertir',
      'mod_action_title': 'Actions modérateur',
      'mod_transparency_title': 'Transparence des actions',
      'mod_transparency_desc':
          'Toutes les actions des modérateurs sont publiques',
      'mod_no_reports': 'Aucun signalement en attente',
      'mod_no_candidates': 'Aucun candidat',
      'mod_no_moderators': 'Aucun modérateur élu',
      'mod_no_sanctions': 'Aucune sanction enregistrée',
      'mod_sanctions_title': 'Journal des sanctions',
      'mod_sanctions_desc':
          'Toutes les sanctions sont publiques et transparentes',
      'mod_sanction_warning': 'Avertissement',
      'mod_sanction_ban': 'Bannissement',
      'mod_sanction_by': 'par',
      'mod_sanction_permanent': 'Permanent',
      'mod_sanction_until': 'Jusqu\'au',
      'mod_vote_for': 'Pour',
      'mod_vote_against': 'Contre',
      'mod_vote_revoke': 'Révoquer',
      'mod_confirm_delete_title': 'Suppression directe',
      'mod_confirm_delete_text':
          'Supprimer ce post immédiatement ?\nCette action est irréversible.',
      'mod_confirm_warn_title': 'Avertir l\'utilisateur',
      'mod_confirm_warn_text':
          'Envoyer un avertissement officiel à cet utilisateur ?',

      // Discovery
      'discover_militants': 'Découvrir des militants',
      'discover_militants_desc':
          'Trouve de nouveaux militants et causes à soutenir',
      'new_militants': 'Nouveaux militants',
      'militants_same_cause': 'Militants de la même cause',
      'suggested_militants': 'Militants suggérés',
      'suggested_groups': 'Groupes suggérés',
      'suggested_pages': 'Pages suggérées',
      'retry': 'Réessayer',
      'subscription_success': 'Abonnement réussi',

      // Additional translations
      'badge_updated': 'Badge mis à jour avec succès',
      'group_created': 'Groupe créé avec succès',
      'new_group': 'Nouveau groupe',
      'create_group': 'Créer le groupe',
      'profile_updated': 'Profil mis à jour avec succès',
      'choose_media': 'Choisir un média',
      'image_from_gallery': 'Image de la galerie',
      'video_from_gallery': 'Vidéo de la galerie',
      'take_photo': 'Prendre une photo',
      'record_video': 'Filmer une vidéo',
      'add_content_or_media': 'Ajoutez du contenu ou un média',
      'name_required': 'Le nom est obligatoire',
      'page_created': 'Page créée avec succès !',
      'settings': 'Paramètres',
      'group_settings': 'Paramètres du groupe',
      'link_copied': 'Lien copié dans le presse-papier',
      'deletion_delay': 'Délai de suppression',
      'disabled': 'Désactivé',
      'confirm_question': 'Confirmer ?',
      'grant_admin_rights':
          'Cela accordera les droits d\'administration à tous les membres actuels du groupe.',
      'remove_member_question': 'Retirer ce membre ?',
      'remove_member_confirm': 'Voulez-vous retirer {username} du groupe ?',
      'leave_group_question': 'Quitter le groupe ?',
      'leave_group_confirm':
          'Êtes-vous sûr de vouloir quitter ce groupe ? Vous ne pourrez plus accéder aux messages.',
      'left_group': 'Vous avez quitté le groupe',
      'social_network':
          'Le réseau social engagé : autogéré, éthique et sans aucun pistage. Conçu pour l\'action collective et la coordination militante sans surveillance.',
      'copyright': '© 2026 Militant - Réseau Social Libre',
      'view_website': 'Voir le site web',
      'source_code': 'Code source',
      'password_changed': 'Mot de passe modifié avec succès',
      'loading_error': 'Erreur chargement',
      'cannot_open_link': 'Impossible d\'ouvrir le lien',
      'error_upload': 'Erreur upload',
      'error_translation': 'Erreur de traduction',
      'audio': 'Audio',
      'link': 'Lien',
      'share_link': 'Partager',
      'enter_6_digit_code': 'Veuillez entrer un code à 6 chiffres',
      'disable_2fa_question': 'Désactiver la 2FA ?',
      'account_less_secure': 'Votre compte sera moins sécurisé.',
      'recovery_codes': 'Codes de récupération',
      'codes_copied': 'Codes copiés',
      'copy_all': 'Copier tout',
      'saved_codes': 'J\'ai enregistré les codes',
      'two_factor_auth': 'Double authentification',
      'secret_copied': 'Secret copié',
      'open_in_authenticator': 'Ouvrir dans l\'authentificateur',
      'enable_2fa': 'Activer la 2FA',
      'disable_2fa': 'Désactiver la 2FA',
      'select_date': 'Veuillez sélectionner une date',
      'event_created': 'Événement créé',
      'logout_question': 'Déconnexion',
      'logout_confirm': 'Voulez-vous vraiment vous déconnecter ?',
      'remove_from_friends': 'Retirer des amis',
      'remove_friend_confirm':
          'Voulez-vous vraiment retirer cette personne de vos amis ?',
      'remove': 'Retirer',
      'discussions': 'Discussions',
      'publications': 'Publications',
      'team': 'Équipe',
      'parameters': 'Paramètres',
      'no_events': 'Aucun événement',
      'no_groups': 'Aucun groupe',
      'no_pages': 'Aucune page',
      'delete_event': 'Supprimer l\'événement',
      'delete_event_confirm': 'Voulez-vous vraiment supprimer cet événement ?',
      'event_deleted': 'Événement supprimé',
      'event': 'Événement',
      'month_jan': 'JAN',
      'month_feb': 'FÉV',
      'month_mar': 'MAR',
      'month_apr': 'AVR',
      'month_may': 'MAI',
      'month_jun': 'JUN',
      'month_jul': 'JUL',
      'month_aug': 'AOÛ',
      'month_sep': 'SEP',
      'month_oct': 'OCT',
      'month_nov': 'NOV',
      'month_dec': 'DÉC',
      'create': 'Créer',
      'join': 'Rejoindre',
      'joined': 'Membre',
      'leave': 'Quitter',
      'members': 'membres',
      'member': 'membre',
      'group': 'Groupe',
      'page': 'Page',
      'description': 'Description',
      'private': 'Privé',
      'public': 'Public',

      // Groups screen
      'error_loading': 'Erreur',
      'create_group_title': 'Créer un groupe',
      'group_name_label': 'Nom du groupe *',
      'group_description_label': 'Description',
      'group_private_label': 'Groupe privé',
      'group_private_subtitle':
          'Seuls les membres approuvés peuvent voir le contenu',
      'group_created_success': 'Groupe créé !',
      'joined_group': 'Vous avez rejoint',
      'no_groups_message': 'Aucun groupe',
      'no_groups_subtitle': 'Rejoignez ou créez un groupe !',
      'discover_groups': 'Découvrir des groupes',
      'no_discover_groups': 'Aucun groupe à découvrir',
      'all_groups_joined': 'Vous êtes membre de tous les groupes !',
      'posts_count': 'post',
      'posts_count_plural': 'posts',

      // Pages screen
      'my_pages': 'Mes pages',
      'followed_pages': 'Suivies',
      'no_pages_message': 'Aucune page',
      'create_page_subtitle': 'Créez une page pour votre cause !',
      'create_page_button': 'Créer une page',
      'no_followed_pages': 'Aucune page suivie',
      'discover_pages': 'Découvrir des pages',
      'no_discover_pages': 'Aucune page à découvrir',
      'follow_button': 'Suivre',
      'following_page': 'Vous suivez',
      'admin_badge': 'Admin',
      'followers_count': 'abonné',
      'followers_count_plural': 'abonnés',

      // Group detail screen
      'group_detail_error': 'Erreur',
      'event_not_found': 'Événement introuvable',
      'no_posts_yet': 'Aucune publication pour le moment',
      'group_settings_title': 'Paramètres du groupe',
      'change_avatar': 'Changer l\'avatar',
      'change_cover': 'Changer la couverture',
      'group_name': 'Nom',
      'group_privacy': 'Privé',
      'view_members': 'Voir les membres',
      'members_title': 'Membres',
      'organized_by': 'Organisé par',
      'publications_title': 'Publications',

      // Event detail screen
      'event_detail_title': 'Événement',
      'date_and_time': 'Date et heure',
      'location': 'Lieu',
      'participants': 'Participants',
      'participant_count': 'participant',
      'participant_count_plural': 'participants',
      'participate_button': 'Participer',
      'participating_status': 'Vous participez ✓',
      'about_event': 'À propos de cet événement',
      'unknown_date': 'Date inconnue',
      'monday': 'Lundi',
      'tuesday': 'Mardi',
      'wednesday': 'Mercredi',
      'thursday': 'Jeudi',
      'friday': 'Vendredi',
      'saturday': 'Samedi',
      'sunday': 'Dimanche',
      'january': 'janvier',
      'february': 'février',
      'march': 'mars',
      'april': 'avril',
      'may': 'mai',
      'june': 'juin',
      'july': 'juillet',
      'august': 'août',
      'september': 'septembre',
      'october': 'octobre',
      'november': 'novembre',
      'december': 'décembre',

      // Create event screen
      'create_event_title': 'Créer un événement',
      'event_title_label': 'Titre',
      'event_description_label': 'Description',
      'event_location_label': 'Lieu',
      'add_image': 'Ajouter une image',
      'select_time': 'Sélectionner une heure (optionnel)',
      'title_required': 'Le titre est requis',
      'date_required': 'Veuillez sélectionner une date',

      // Page detail screen
      'post_added': 'Publication ajoutée !',
      'delete_post_question': 'Supprimer la publication ?',
      'action_irreversible': 'Cette action est irréversible.',
      'post_deleted': 'Publication supprimée',
      'edit_post_title': 'Modifier la publication',
      'post_content_hint': 'Contenu de la publication...',
      'post_updated': 'Publication modifiée',
      'settings_saved': 'Paramètres enregistrés !',
      'remove_follower_question': 'Retirer cet abonné ?',
      'admin_editor_description':
          'Les admins peuvent tout faire. Les éditeurs peuvent publier mais pas modifier les paramètres.',
      'admin_full_control':
          'Les admins ont plein contrôle sur la page et les membres.',
      'editor_limited_access':
          'Les éditeurs peuvent publier mais pas gérer les membres ni les paramètres.',
      'private_followers_only': 'Privée - Abonnés uniquement',
      'no_posts_message': 'Aucune publication',
      'no_followers': 'Aucun abonné',
      'no_comments': 'Aucun commentaire',
      'subscribed': 'Abonné',
      'subscribe': 'Suivre',
      'follower': 'abonné',
      'followers_plural': 'abonnés',

      // Create page screen
      'create_page_title': 'Créer une page',
      'create_page_for_cause': 'Créez une page pour votre cause',
      'name_field': 'Nom *',
      'page_name_hint': 'Nom de la page',
      'category_field': 'Catégorie',
      'description_field': 'Description',
      'describe_page_hint': 'Décrivez votre page...',
      'creating': 'Création...',
      'category_union': 'Syndicat',
      'category_collective': 'Collectif',
      'category_association': 'Association',
      'category_media': 'Média',
      'category_squat': 'Squat / Lieu',
      'category_infokiosk': 'Infokiosque',
      'category_artist': 'Artiste',
      'category_project': 'Projet',
      'category_other': 'Autre',

      // Moderation additional keys
      'mod_already_moderator': 'Tu es déjà modérateur·ice !',
      'mod_already_candidate': 'Tu es déjà candidat·e !',
      'mod_cancel_candidacy': 'Annuler ma candidature',
      'mod_cancel_candidacy_question': 'Annuler la candidature ?',
      'mod_cancel_candidacy_warning':
          'Veux-tu vraiment retirer ta candidature ?\nTu perdras tous les votes reçus.',
      'mod_candidacy_cancelled': 'Candidature annulée.',
      'mod_vote_recorded': 'Vote enregistré !',
      'mod_elected_consensus': 'Modérateur·ice élu·e par consensus !',
      'mod_revoked_consensus': 'Modérateur·ice révoqué·e par consensus !',
      'mod_post_deleted_action': 'Post supprimé par action de modérateur',
      'mod_no_actions': 'Aucune action enregistrée',
      'mod_your_candidacy': 'C\'est ta candidature',
      'promote_to_admin': 'Nommer admin',
      'promote_to_admin_question': 'Nommer {username} admin ?',
      'demote_to_editor': 'Rétrograder',
      'demote_to_editor_question':
          'Rétrograder {username} au rôle d\'éditeur ?',
      'add_member': 'Ajouter un membre',
      'add': 'Ajouter',
      'add_media': 'Ajouter un média',
      'add_cover': 'Ajouter une couverture',
      'page_name': 'Nom de la page',
      'category': 'Catégorie',
      'remove_member': 'Retirer',
      'remove_member_title': 'Retirer ce membre ?',
      'remove_follower_title': 'Retirer cet abonné ?',

      // Search screen
      'search_users_posts': 'Recherchez des utilisateurs ou des posts',
      'no_results': 'Aucun résultat',
      'users_tab': 'Utilisateurs',
      'posts_tab': 'Posts',
      'just_now': 'À l\'instant',
      'unknown_user': 'utilisateur',

      // Notifications screen
      'no_notifications': 'Aucune notification',
      'notification_like': 'a aimé votre post',
      'notification_comment': 'a commenté votre post',
      'notification_follow': 'a commencé à vous suivre',
      'notification_mention': 'vous a mentionné',
      'notification_reaction': 'a réagi à votre post',
      'notification_message': 'vous a envoyé un message',
      'notification_message_request': 'vous a envoyé une demande de message',
      'notification_friend_request': 'vous a envoyé une demande d\'ami',
      'notification_friend_accept': 'a accepté votre demande d\'ami',
      'notification_group_invite': 'vous a invité à rejoindre un groupe',
      'notification_event_invite': 'vous a invité à un événement',
      'notification_post_share': 'a partagé votre post',
      'notification_generic': 'notification',
      'minutes_short': 'min',
      'hours_short': 'h',
      'days_short': 'j',
      'reply': 'Répondre',
      'reply_to': 'Répondre à {username}',
      'replies': 'réponses',
      'reply_count': '{count} réponse',
      'reply_count_plural': '{count} réponses',

      // Appels (privés et de groupe)
      'call_audio': 'Appel audio',
      'call_video': 'Appel vidéo',
      'call_group_audio': 'Appel audio de groupe',
      'call_group_video': 'Appel vidéo de groupe',
      'call_connecting': 'Connexion...',
      'call_ringing': 'Appel en cours...',
      'call_active': 'Connecté',
      'call_ended': 'Appel terminé',
      'call_rejected': 'Appel rejeté',
      'call_missed': 'Appel manqué',
      'call_incoming': 'Appel entrant',
      'call_answer': 'Répondre',
      'call_decline': 'Refuser',
      'call_end': 'Raccrocher',
      'call_mute': 'Couper le micro',
      'call_unmute': 'Activer le micro',
      'call_camera_on': 'Caméra activée',
      'call_camera_off': 'Caméra désactivée',
      'call_switch_camera': 'Changer de caméra',
      'call_participants': 'Participants',
      'call_participant_count': '{count} participant(s)',
      'call_joining': 'Jonction en cours...',
      'call_network_reconnecting': 'Reconnexion en cours...',
      'call_you': 'Vous',
      'call_history': 'Historique des appels',
      'call_duration': 'Durée',
      'call_incoming_from': 'Appel entrant de {name}',
      'call_group_incoming': 'Appel de groupe dans {group}',
    },
    'en': {
      // General
      'app_title': 'Militant',
      'cancel': 'Cancel',
      'save': 'Save',
      'error': 'Error',
      'loading': 'Loading...',
      'success': 'Success',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'report': 'Report',
      'share': 'Share',
      'edit': 'Edit',
      'close': 'Close',
      'settings_updated': 'Settings updated',

      // Auth
      'login_title': 'Login',
      'email_label': 'Email',
      'password_label': 'Password',
      'login_button': 'Login',
      'register_link': 'No account? Register',
      'register_title': 'Register',
      'create_account': 'Create an account',
      'join_community': 'Join the militant community',
      'username_label': 'Username',
      'register_button': 'Register',
      'login_link': 'Already have an account? Login',
      'password_required': 'Password required',
      'email_required': 'Email required',
      'confirm_password': 'Confirm password',
      'your_main_cause': 'Your main cause',
      'choose_cause': 'Choose a cause',

      // Home & Navigation
      'home_title': 'Home',
      'messages_title': 'Chat',
      'profile_title': 'Profile',
      'settings_title': 'Settings',
      'groups_title': 'Groups',
      'events_title': 'Events',
      'pages_title': 'Pages',
      'notifications_title': 'Notifs',
      'test_notifications': 'Test Notifications',
      'test_notifications_desc': 'Send a test push notification now',
      'notification_test_sent': 'Test sent! Check your notifications.',
      'friends_title': 'Friends',
      'friend_requests': 'Requests',
      'accept': 'Accept',
      'decline': 'Decline',
      'search_hint': 'Search...',
      'discover': 'Discover',
      'community_tab_title': 'Community',
      'explore_mobilize_title': 'Explore and Mobilize',
      'groups_desc': 'Join the local struggle and organize.',
      'events_desc': 'Protests, assemblies, and actions.',
      'pages_desc': 'Follow collectives and organizations.',
      'moderation_desc': 'Manage reports and security.',
      'feed_tab_discover': 'Discover',
      'feed_tab_following': 'Following',
      'empty_feed_following':
          "No posts in your following feed.\nSubscribe or go to 'Discover'!",
      'empty_feed_global': 'No posts available at the moment.',

      // Posts
      'create_post_title': 'New Post',
      'create_post_hint': 'What\'s on your mind?',
      'publish_button': 'Publish',
      'post_detail_title': 'Post',
      'comments_title': 'Comments',
      'comment_hint': 'Add a comment...',
      'like_action': 'Like',
      'comment_action': 'Comment',
      'share_action': 'Share',
      'delete_post_confirm': 'Do you really want to delete this post?',
      'report_post_title': 'Report Post',
      'report_reason_hint': 'Reason for reporting',
      'report_submit': 'Submit',

      // Profile
      'edit_profile_title': 'Edit Profile',
      'edit_profile_subtitle': 'Bio, website and social networks',
      'profile_info_title': 'Profile Information',
      'bio_label': 'Biography',
      'bio_hint': 'Tell us about yourself...',
      'website_label': 'Website',
      'location_label': 'Location',
      'location_hint': 'City, Country',
      'social_links_title': 'Social Networks',
      'save_button': 'Save',
      'saved_posts_title': 'Saved Posts',
      'posts': 'Posts',
      'media': 'Media',
      'followers': 'Followers',
      'following': 'Following',
      'no_posts': 'No posts',
      'no_media': 'No media',
      'logout': 'Logout',

      // Settings
      'security_title': 'Security',
      'privacy_title': 'Privacy',
      'language_title': 'Language',
      'theme_title': 'Theme',
      'about_title': 'About',
      'theme_dark': 'Dark',
      'theme_light': 'Light',
      'choose_language': 'Choose language',
      'choose_theme': 'Choose theme',
      'subtitle_notifications': 'Manage notifications',
      'subtitle_security': 'Change password',
      'subtitle_privacy': 'Privacy settings',
      'version': 'Version 1.0.5',

      // Notifications Settings
      'notifications_push': 'Push notifications',
      'notifications_push_subtitle': 'On this device',
      'notifications_email': 'Emails',
      'notifications_email_subtitle': 'Receive email summaries',
      'notifications_likes': 'Likes',
      'notifications_likes_subtitle': 'When someone likes your posts',
      'notifications_comments': 'Comments',
      'notifications_comments_subtitle': 'When someone comments',
      'notifications_messages': 'Private and group messages',
      'notifications_messages_subtitle':
          'New private messages and group chat messages',
      'notifications_friend_requests': 'Friend requests',
      'notifications_friend_requests_subtitle':
          'New friend requests and accepted requests',
      'notifications_follows': 'Follows',
      'notifications_follows_subtitle': 'New followers',
      'notifications_mentions': 'Mentions',
      'notifications_mentions_subtitle': 'When you are mentioned',
      'notifications_channels_title': 'CHANNELS',
      'notifications_interactions_title': 'INTERACTIONS',

      // Privacy Settings
      'privacy_private_account': 'Private account',
      'privacy_private_subtitle': 'Only followers can see your posts and media',
      'privacy_allow_messages': 'Direct messages',
      'privacy_allow_messages_subtitle': 'Allow everyone to send you messages',
      'privacy_online_status': 'Online status',
      'privacy_online_subtitle': 'Show when you are active',
      'privacy_read_receipts': 'Read receipts',
      'privacy_read_receipts_subtitle': 'See when messages are read',

      // Change Password
      'change_password_title': 'Change password',
      'current_password': 'Current password',
      'new_password': 'New password',
      'password_match_error': 'Passwords do not match',
      'password_min_length': 'Minimum 8 characters',
      'update_button': 'Update',
      'password_updated': 'Password updated successfully',

      // Chat
      'message_hint': 'Message...',
      'message_group_hint': 'Message to the group...',
      'online': 'Online',
      'private_account_title': 'This account is private',
      'private_account_subtitle': 'Follow this account to see their posts.',
      'no_messages': 'No messages',
      'no_group_messages': 'No messages in this group',
      'no_conversations': 'No conversations',
      'no_group_discussions': 'No discussion groups',
      'user': 'User',
      'anonymous_user': 'Anonymous',
      'me_label': 'Me',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'delete_question': 'Delete?',
      'delete_message_confirm': 'Do you want to delete this message?',
      'delete_conversation_confirm':
          'Do you want to delete this entire conversation? This action is permanent.',
      'conversation_deleted': 'Conversation deleted',
      'edit_message': 'Edit message',
      'translate_action': 'Translate',
      'original_label': 'Original',
      'edited_label': 'Edited',
      'ephemeral_minutes': 'Ephemeral: {minutes} min',
      'follow': 'Follow',
      'following_status': 'Following',

      // Stories
      'stories_add': 'Add',
      'stories_created': 'Story created',
      'stories_error': 'Error',
      'stories_title': 'Stories',

      // Badge Selection
      'my_militant_badge': 'Badge',
      'no_badge': 'No badge',
      'select_badge_text': 'Affiliation',
      'export_data_title': 'Export',
      'export_data_subtitle': 'JSON Download',
      'two_factor_title': '2FA Auth.',
      'two_factor_subtitle': 'TOTP Code',
      'delete_account_title': 'Delete my account',
      'delete_account_subtitle': 'Request permanent deletion',
      'delete_account_confirm': 'Delete permanently',
      'delete_account_warning':
          'Warning: This action is irreversible. All your data will be erased. A confirmation email will be sent.',
      'enter_password_to_delete': 'Enter your password to confirm',
      'delete_account_request_sent':
          'Request sent! Check your emails to confirm.',

      // Moderation
      'mod_title': 'Moderation',
      'mod_tab_reports': 'Reports',
      'mod_tab_candidates': 'Candidates',
      'mod_tab_moderators': 'Moderators',
      'mod_tab_sanctions': 'Sanctions',
      'mod_principles_title': 'Moderation Principles',
      'mod_principles_text':
          '• Total equality\n• No hierarchy\n• Consensus decisions (70%)\n• Everyone can vote\n• Revocable moderators',
      'mod_apply_btn': 'Apply for Moderator',
      'mod_apply_dialog_title': 'Apply for Moderator',
      'mod_apply_dialog_desc': 'Explain why you want to become a moderator:',
      'mod_apply_hint': 'Your motivation...',
      'mod_apply_send': 'Send',
      'mod_apply_cancel': 'Cancel',
      'mod_apply_success': 'Application sent!',
      'mod_vote_remove': 'Remove',
      'mod_vote_warn': 'Warn',
      'mod_vote_keep': 'Keep',
      'mod_action_direct_delete': 'Direct Delete',
      'mod_action_warn': 'Warn',
      'mod_action_title': 'Moderator Actions',
      'mod_transparency_title': 'Action Transparency',
      'mod_transparency_desc': 'All moderator actions are public',
      'mod_no_reports': 'No pending reports',
      'mod_no_candidates': 'No candidates',
      'mod_no_moderators': 'No elected moderators',
      'mod_no_sanctions': 'No sanctions recorded',
      'mod_sanctions_title': 'Sanctions Log',
      'mod_sanctions_desc': 'All sanctions are public and transparent',
      'mod_sanction_warning': 'Warning',
      'mod_sanction_ban': 'Ban',
      'mod_sanction_by': 'by',
      'mod_sanction_permanent': 'Permanent',
      'mod_sanction_until': 'Until',
      'mod_vote_for': 'For',
      'mod_vote_against': 'Against',
      'mod_vote_revoke': 'Revoke',
      'mod_confirm_delete_title': 'Direct Delete',
      'mod_confirm_delete_text':
          'Delete this post immediately?\nThis action is irreversible.',
      'mod_confirm_warn_title': 'Warn User',
      'mod_confirm_warn_text': 'Send an official warning to this user?',

      // Discovery
      'discover_militants': 'Discover militants',
      'discover_militants_desc': 'Find new militants and causes to support',
      'new_militants': 'New militants',
      'militants_same_cause': 'Militants of the same cause',
      'suggested_militants': 'Suggested militants',
      'suggested_groups': 'Suggested groups',
      'suggested_pages': 'Suggested pages',
      'retry': 'Retry',
      'subscription_success': 'Subscription successful',

      // Additional translations
      'badge_updated': 'Badge updated successfully',
      'group_created': 'Group created successfully',
      'new_group': 'New group',
      'create_group': 'Create group',
      'profile_updated': 'Profile updated successfully',
      'choose_media': 'Choose media',
      'image_from_gallery': 'Image from gallery',
      'video_from_gallery': 'Video from gallery',
      'take_photo': 'Take a photo',
      'record_video': 'Record a video',
      'add_content_or_media': 'Add content or media',
      'name_required': 'Name is required',
      'page_created': 'Page created successfully!',
      'settings': 'Settings',
      'group_settings': 'Group settings',
      'link_copied': 'Link copied to clipboard',
      'deletion_delay': 'Deletion delay',
      'disabled': 'Disabled',
      'confirm_question': 'Confirm?',
      'grant_admin_rights':
          'This will grant admin rights to all current group members.',
      'remove_member_question': 'Remove this member?',
      'remove_member_confirm':
          'Do you want to remove {username} from the group?',
      'leave_group_question': 'Leave group?',
      'leave_group_confirm':
          'Are you sure you want to leave this group? You will no longer have access to messages.',
      'left_group': 'You left the group',
      'social_network':
          'The committed social network: self-managed, ethical, and tracker-free. Designed for collective action and grassroots coordination without surveillance.',
      'copyright': '© 2026 Militant - Free Social Network',
      'view_website': 'View Website',
      'source_code': 'Source Code',
      'password_changed': 'Password changed successfully',
      'loading_error': 'Loading error',
      'cannot_open_link': 'Cannot open link',
      'error_upload': 'Upload error',
      'error_translation': 'Translation error',
      'audio': 'Audio',
      'link': 'Link',
      'share_link': 'Share',
      'enter_6_digit_code': 'Please enter a 6-digit code',
      'disable_2fa_question': 'Disable 2FA?',
      'account_less_secure': 'Your account will be less secure.',
      'recovery_codes': 'Recovery codes',
      'codes_copied': 'Codes copied',
      'copy_all': 'Copy all',
      'saved_codes': 'I saved the codes',
      'two_factor_auth': 'Two-factor authentication',
      'secret_copied': 'Secret copied',
      'open_in_authenticator': 'Open in authenticator',
      'enable_2fa': 'Enable 2FA',
      'disable_2fa': 'Disable 2FA',
      'select_date': 'Please select a date',
      'event_created': 'Event created',
      'logout_question': 'Logout',
      'logout_confirm': 'Do you really want to logout?',
      'remove_from_friends': 'Remove from friends',
      'remove_friend_confirm':
          'Do you really want to remove this person from your friends?',
      'remove': 'Remove',
      'add_friend': 'Add friend',
      'friend_request_sent': 'Request sent',
      'friend_request_received': 'Friend request received',
      'message': 'Message',
      'friends': 'Friends',
      'discussions': 'Chats',
      'publications': 'Publications',
      'team': 'Team',
      'parameters': 'Settings',
      'no_events': 'No events',
      'no_groups': 'No groups',
      'no_pages': 'No pages',
      'delete_event': 'Delete event',
      'delete_event_confirm': 'Do you really want to delete this event?',
      'event_deleted': 'Event deleted',
      'event': 'Event',
      'month_jan': 'JAN',
      'month_feb': 'FEB',
      'month_mar': 'MAR',
      'month_apr': 'APR',
      'month_may': 'MAY',
      'month_jun': 'JUN',
      'month_jul': 'JUL',
      'month_aug': 'AUG',
      'month_sep': 'SEP',
      'month_oct': 'OCT',
      'month_nov': 'NOV',
      'month_dec': 'DEC',
      'create': 'Create',
      'join': 'Join',
      'joined': 'Member',
      'leave': 'Leave',
      'members': 'members',
      'member': 'member',
      'group': 'Group',
      'page': 'Page',
      'description': 'Description',
      'private': 'Private',
      'public': 'Public',

      // Groups screen
      'error_loading': 'Error',
      'create_group_title': 'Create a group',
      'group_name_label': 'Group name *',
      'group_description_label': 'Description',
      'group_private_label': 'Private group',
      'group_private_subtitle': 'Only approved members can see content',
      'group_created_success': 'Group created!',
      'joined_group': 'You joined',
      'no_groups_message': 'No groups',
      'no_groups_subtitle': 'Join or create a group!',
      'discover_groups': 'Discover groups',
      'no_discover_groups': 'No groups to discover',
      'all_groups_joined': 'You are a member of all groups!',
      'posts_count': 'post',
      'posts_count_plural': 'posts',

      // Pages screen
      'my_pages': 'My pages',
      'followed_pages': 'Followed',
      'no_pages_message': 'No pages',
      'create_page_subtitle': 'Create a page for your cause!',
      'create_page_button': 'Create a page',
      'no_followed_pages': 'No followed pages',
      'discover_pages': 'Discover pages',
      'no_discover_pages': 'No pages to discover',
      'follow_button': 'Follow',
      'following_page': 'You follow',
      'admin_badge': 'Admin',
      'followers_count': 'follower',
      'followers_count_plural': 'followers',

      // Group detail screen
      'group_detail_error': 'Error',
      'event_not_found': 'Event not found',
      'no_posts_yet': 'No posts yet',
      'group_settings_title': 'Group settings',
      'change_avatar': 'Change avatar',
      'change_cover': 'Change cover',
      'group_name': 'Name',
      'group_privacy': 'Private',
      'view_members': 'View members',
      'members_title': 'Members',
      'organized_by': 'Organized by',
      'publications_title': 'Publications',

      // Event detail screen
      'event_detail_title': 'Event',
      'date_and_time': 'Date and time',
      'location': 'Location',
      'participants': 'Participants',
      'participant_count': 'participant',
      'participant_count_plural': 'participants',
      'participate_button': 'Participate',
      'participating_status': 'You are participating ✓',
      'about_event': 'About this event',
      'unknown_date': 'Unknown date',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',

      // Create event screen
      'create_event_title': 'Create an event',
      'event_title_label': 'Title',
      'event_description_label': 'Description',
      'event_location_label': 'Location',
      'add_image': 'Add an image',
      'select_time': 'Select a time (optional)',
      'title_required': 'Title is required',
      'date_required': 'Please select a date',

      // Page detail screen
      'post_added': 'Post added!',
      'delete_post_question': 'Delete post?',
      'action_irreversible': 'This action is irreversible.',
      'post_deleted': 'Post deleted',
      'edit_post_title': 'Edit post',
      'post_content_hint': 'Post content...',
      'post_updated': 'Post updated',
      'settings_saved': 'Settings saved!',
      'remove_follower_question': 'Remove this follower?',
      'admin_editor_description':
          'Admins can do everything. Editors can post but not modify settings.',
      'admin_full_control':
          'Admins have full control over the page and members.',
      'editor_limited_access':
          'Editors can post but not manage members or settings.',
      'private_followers_only': 'Private - Followers only',
      'no_posts_message': 'No posts',
      'no_followers': 'No followers',
      'no_comments': 'No comments',
      'subscribed': 'Subscribed',
      'subscribe': 'Subscribe',
      'follower': 'follower',
      'followers_plural': 'followers',

      // Create page screen
      'create_page_title': 'Create a page',
      'create_page_for_cause': 'Create a page for your cause',
      'name_field': 'Name *',
      'page_name_hint': 'Page name',
      'category_field': 'Category',
      'description_field': 'Description',
      'describe_page_hint': 'Describe your page...',
      'creating': 'Creating...',
      'category_union': 'Union',
      'category_collective': 'Collective',
      'category_association': 'Association',
      'category_media': 'Media',
      'category_squat': 'Squat / Place',
      'category_infokiosk': 'Infokiosk',
      'category_artist': 'Artist',
      'category_project': 'Project',
      'category_other': 'Other',

      // Moderation additional keys
      'mod_already_moderator': 'You are already a moderator!',
      'mod_already_candidate': 'You are already a candidate!',
      'mod_cancel_candidacy': 'Cancel my candidacy',
      'mod_cancel_candidacy_question': 'Cancel candidacy?',
      'mod_cancel_candidacy_warning':
          'Do you really want to withdraw your candidacy?\nYou will lose all votes received.',
      'mod_candidacy_cancelled': 'Candidacy cancelled.',
      'mod_vote_recorded': 'Vote recorded!',
      'mod_elected_consensus': 'Moderator elected by consensus!',
      'mod_revoked_consensus': 'Moderator revoked by consensus!',
      'mod_post_deleted_action': 'Post deleted by moderator action',
      'mod_no_actions': 'No actions recorded',
      'mod_your_candidacy': 'This is your candidacy',
      'promote_to_admin': 'Promote to Admin',
      'promote_to_admin_question': 'Promote {username} to admin?',
      'demote_to_editor': 'Demote',
      'demote_to_editor_question': 'Demote {username} to editor role?',
      'add_member': 'Add a member',
      'add': 'Add',
      'add_media': 'Add media',
      'add_cover': 'Add a cover',
      'page_name': 'Page name',
      'category': 'Category',
      'remove_member': 'Remove',
      'remove_member_title': 'Remove this member?',
      'remove_follower_title': 'Remove this follower?',

      // Search screen
      'search_users_posts': 'Search for users or posts',
      'no_results': 'No results',
      'users_tab': 'Users',
      'posts_tab': 'Posts',
      'just_now': 'Just now',
      'unknown_user': 'user',

      // Notifications screen
      'no_notifications': 'No notifications',
      'notification_like': 'liked your post',
      'notification_comment': 'commented on your post',
      'notification_follow': 'started following you',
      'notification_mention': 'mentioned you',
      'notification_reaction': 'reacted to your post',
      'notification_message': 'sent you a message',
      'notification_message_request': 'sent you a message request',
      'notification_friend_request': 'sent you a friend request',
      'notification_friend_accept': 'accepted your friend request',
      'notification_group_invite': 'invited you to join a group',
      'notification_event_invite': 'invited you to an event',
      'notification_post_share': 'shared your post',
      'notification_generic': 'notification',
      'minutes_short': 'min',
      'hours_short': 'h',
      'days_short': 'd',
      'reply': 'Reply',
      'reply_to': 'Reply to {username}',
      'replies': 'replies',
      'reply_count': '{count} reply',
      'reply_count_plural': '{count} replies',

      // Calls (1-to-1 and group)
      'call_audio': 'Audio call',
      'call_video': 'Video call',
      'call_group_audio': 'Group audio call',
      'call_group_video': 'Group video call',
      'call_connecting': 'Connecting...',
      'call_ringing': 'Ringing...',
      'call_active': 'Connected',
      'call_ended': 'Call ended',
      'call_rejected': 'Call rejected',
      'call_missed': 'Missed call',
      'call_incoming': 'Incoming call',
      'call_answer': 'Answer',
      'call_decline': 'Decline',
      'call_end': 'End call',
      'call_mute': 'Mute',
      'call_unmute': 'Unmute',
      'call_camera_on': 'Camera on',
      'call_camera_off': 'Camera off',
      'call_switch_camera': 'Switch camera',
      'call_participants': 'Participants',
      'call_participant_count': '{count} participant(s)',
      'call_joining': 'Joining...',
      'call_network_reconnecting': 'Reconnecting...',
      'call_you': 'You',
      'call_history': 'Call history',
      'call_duration': 'Duration',
      'call_incoming_from': 'Incoming call from {name}',
      'call_group_incoming': 'Group call in {group}',
    },
    'es': {
      // General
      'app_title': 'Militante',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'error': 'Error',
      'loading': 'Cargando...',
      'success': 'Éxito',
      'confirm': 'Confirmar',
      'delete': 'Eliminar',
      'report': 'Reportar',
      'share': 'Compartir',
      'edit': 'Editar',
      'close': 'Cerrar',
      'settings_updated': 'Ajustes actualizados',

      // Auth
      'login_title': 'Iniciar sesión',
      'email_label': 'Correo electrónico',
      'password_label': 'Contraseña',
      'login_button': 'Iniciar sesión',
      'register_link': '¿No tienes cuenta? Regístrate',
      'register_title': 'Registro',
      'create_account': 'Crear una cuenta',
      'join_community': 'Únete a la comunidad militante',
      'username_label': 'Nombre de usuario',
      'register_button': 'Registrarse',
      'login_link': '¿Ya tienes cuenta? Inicia sesión',
      'password_required': 'Contraseña requerida',
      'email_required': 'Correo requerido',
      'confirm_password': 'Confirmar contraseña',
      'your_main_cause': 'Tu causa principal',
      'choose_cause': 'Elegir una causa',

      // Home & Navigation
      'home_title': 'Inicio',
      'messages_title': 'Chat',
      'profile_title': 'Perfil',
      'settings_title': 'Ajustes',
      'groups_title': 'Grupos',
      'events_title': 'Eventos',
      'pages_title': 'Páginas',
      'notifications_title': 'Notif.',
      'test_notifications': 'Probar notificaciones',
      'test_notifications_desc': 'Enviar una notificación de prueba ahora',
      'notification_test_sent': '¡Prueba enviada! Revisa tus notificaciones.',
      'friends_title': 'Amigos',
      'friend_requests': 'Solicit.',
      'accept': 'Aceptar',
      'decline': 'Rechazar',
      'search_hint': 'Buscar...',
      'discover': 'Descubrir',
      'community_tab_title': 'Comunidad',
      'explore_mobilize_title': 'Explora y Movilízate',
      'groups_desc': 'Únete a la lucha local y organízate.',
      'events_desc': 'Manifestaciones, asambleas y acciones.',
      'pages_desc': 'Sigue a colectivos y organizaciones.',
      'moderation_desc': 'Gestiona reportes y seguridad.',
      'feed_tab_discover': 'Descubrir',
      'feed_tab_following': 'Siguiendo',
      'empty_feed_following':
          "No hay publicaciones en tu feed.\n¡Suscríbete o ve a 'Descubrir'!",
      'empty_feed_global': 'No hay publicaciones disponibles por el momento.',

      // Posts
      'create_post_title': 'Nueva publicación',
      'create_post_hint': '¿Qué estás pensando?',
      'publish_button': 'Publicar',
      'post_detail_title': 'Publicación',
      'comments_title': 'Comentarios',
      'comment_hint': 'Añadir un comentario...',
      'like_action': 'Me gusta',
      'comment_action': 'Comentar',
      'share_action': 'Compartir',
      'delete_post_confirm': '¿Realmente quieres eliminar esta publicación?',
      'report_post_title': 'Reportar publicación',
      'report_reason_hint': 'Razón del reporte',
      'report_submit': 'Enviar',

      // Profile
      'edit_profile_title': 'Editar perfil',
      'edit_profile_subtitle': 'Biografía, sitio web y redes sociales',
      'profile_info_title': 'Información del perfil',
      'bio_label': 'Biografía',
      'bio_hint': 'Cuéntanos sobre ti...',
      'website_label': 'Sitio web',
      'location_label': 'Ubicación',
      'location_hint': 'Ciudad, País',
      'social_links_title': 'Redes sociales',
      'save_button': 'Guardar',
      'saved_posts_title': 'Publicaciones guardadas',
      'posts': 'Publicaciones',
      'media': 'Multimedia',
      'followers': 'Seguidores',
      'following': 'Siguiendo',
      'no_posts': 'No hay publicaciones',
      'no_media': 'No hay multimedia',
      'logout': 'Cerrar sesión',

      // Settings
      'security_title': 'Seguridad',
      'privacy_title': 'Privacidad',
      'language_title': 'Idioma',
      'theme_title': 'Tema',
      'about_title': 'Acerca de',
      'theme_dark': 'Oscuro',
      'theme_light': 'Claro',
      'choose_language': 'Elegir idioma',
      'choose_theme': 'Elegir tema',
      'subtitle_notifications': 'Gestionar notificaciones',
      'subtitle_security': 'Cambiar contraseña',
      'subtitle_privacy': 'Configuración de privacidad',
      'version': 'Versión 1.0.5',

      // Notifications Settings
      'notifications_push': 'Notificaciones push',
      'notifications_push_subtitle': 'En este dispositivo',
      'notifications_email': 'Correos electrónicos',
      'notifications_email_subtitle': 'Recibir resúmenes por correo',
      'notifications_likes': 'Me gusta',
      'notifications_likes_subtitle':
          'Cuando a alguien le gusta tu publicación',
      'notifications_comments': 'Comentarios',
      'notifications_comments_subtitle': 'Cuando alguien comenta',
      'notifications_messages': 'Mensajes privados y de grupos',
      'notifications_messages_subtitle':
          'Nuevos mensajes privados y de grupos',
      'notifications_friend_requests': 'Solicitudes de amistad',
      'notifications_friend_requests_subtitle':
          'Nuevas solicitudes y aceptaciones de amistad',
      'notifications_follows': 'Seguidores',
      'notifications_follows_subtitle': 'Nuevos seguidores',
      'notifications_mentions': 'Menciones',
      'notifications_mentions_subtitle': 'Cuando te mencionan',
      'notifications_channels_title': 'CANALES',
      'notifications_interactions_title': 'INTERACCIONES',

      // Privacy Settings
      'privacy_private_account': 'Cuenta privada',
      'privacy_private_subtitle':
          'Solo los seguidores pueden ver tus publicaciones',
      'privacy_allow_messages': 'Mensajes directos',
      'privacy_allow_messages_subtitle':
          'Permitir que todos te envíen mensajes',
      'privacy_online_status': 'Estado en línea',
      'privacy_online_subtitle': 'Mostrar cuando estás activo',
      'privacy_read_receipts': 'Confirmaciones de lectura',
      'privacy_read_receipts_subtitle': 'Ver cuando se leen los mensajes',

      // Change Password
      'change_password_title': 'Cambiar contraseña',
      'current_password': 'Contraseña actual',
      'new_password': 'Nueva contraseña',
      'password_match_error': 'Las contraseñas no coinciden',
      'password_min_length': 'Mínimo 8 caracteres',
      'update_button': 'Actualizar',
      'password_updated': 'Contraseña actualizada con éxito',

      // Chat
      'message_hint': 'Mensaje...',
      'message_group_hint': 'Mensaje al grupo...',
      'online': 'En línea',
      'private_account_title': 'Esta cuenta es privada',
      'private_account_subtitle':
          'Sigue a esta cuenta para ver sus publicaciones.',
      'private_group_title': 'Este grupo es privado',
      'private_group_subtitle':
          'Únete a este grupo para ver sus publicaciones.',
      'no_messages': 'No hay mensajes',
      'no_group_messages': 'No hay mensajes en este grupo',
      'no_conversations': 'No hay conversaciones',
      'no_group_discussions': 'No hay grupos de discusión',
      'user': 'Usuario',
      'anonymous_user': 'Anónimo',
      'me_label': 'Yo',
      'gallery': 'Galería',
      'camera': 'Cámara',
      'delete_question': '¿Eliminar?',
      'delete_message_confirm': '¿Quieres eliminar este mensaje?',
      'delete_conversation_confirm':
          '¿Quieres eliminar toda esta conversación? Esta acción es permanente.',
      'conversation_deleted': 'Conversación eliminada',
      'edit_message': 'Editar mensaje',
      'translate_action': 'Traducir',
      'original_label': 'Original',
      'edited_label': 'Editado',
      'ephemeral_minutes': 'Efímero: {minutes} min',
      'follow': 'Seguir',
      'following_status': 'Siguiendo',

      // Stories
      'stories_add': 'Añadir',
      'stories_created': 'Historia creada',
      'stories_error': 'Error',
      'stories_title': 'Historias',

      // Badge Selection
      'my_militant_badge': 'Insignia',
      'no_badge': 'Sin insignia',
      'select_badge_text': 'Afiliación',
      'export_data_title': 'Exportar',
      'export_data_subtitle': 'Copia JSON',
      'two_factor_title': 'Autenticación (2FA)',
      'two_factor_subtitle': 'Código TOTP',
      'delete_account_title': 'Eliminar mi cuenta',
      'delete_account_subtitle': 'Solicitar eliminación definitiva',
      'delete_account_confirm': 'Eliminar definitivamente',
      'delete_account_warning':
          'Atención: Esta acción es irreversible. Se borrarán todos tus datos. Se enviará un correo de confirmación.',
      'enter_password_to_delete': 'Introduce tu contraseña para confirmar',
      'delete_account_request_sent':
          '¡Solicitud enviada! Revisa tu correo para confirmar.',

      // Additional translations
      'badge_updated': 'Insignia actualizada con éxito',
      'group_created': 'Grupo creado con éxito',
      'new_group': 'Nuevo grupo',
      'create_group': 'Crear grupo',
      'profile_updated': 'Perfil actualizado con éxito',
      'choose_media': 'Elegir medio',
      'image_from_gallery': 'Imagen de la galería',
      'video_from_gallery': 'Video de la galería',
      'take_photo': 'Tomar una foto',
      'record_video': 'Grabar un video',
      'add_content_or_media': 'Añade contenido o medio',
      'name_required': 'El nombre es obligatorio',
      'page_created': '¡Página creada con éxito!',
      'settings': 'Ajustes',
      'group_settings': 'Ajustes del grupo',
      'link_copied': 'Enlace copiado al portapapeles',
      'deletion_delay': 'Retraso de eliminación',
      'disabled': 'Desactivado',
      'confirm_question': '¿Confirmar?',
      'grant_admin_rights':
          'Esto otorgará derechos de administrador a todos los miembros actuales del grupo.',
      'remove_member_question': '¿Eliminar este miembro?',
      'remove_member_confirm': '¿Quieres eliminar a {username} del grupo?',
      'leave_group_question': '¿Salir del grupo?',
      'leave_group_confirm':
          '¿Estás seguro de que quieres salir de este grupo? Ya no tendrás acceso a los mensajes.',
      'left_group': 'Has salido del grupo',
      'social_network':
          'La red social comprometida: autogestionada, ética y sin rastreadores. Diseñada para la acción colectiva y la coordinación militante sin vigilancia.',
      'copyright': '© 2026 Militant - Red Social Libre',
      'view_website': 'Ver sitio web',
      'source_code': 'Código fuente',
      'password_changed': 'Contraseña cambiada con éxito',
      'loading_error': 'Error de carga',
      'cannot_open_link': 'No se puede abrir el enlace',
      'error_upload': 'Error de carga',
      'error_translation': 'Error de traducción',
      'audio': 'Audio',
      'link': 'Enlace',
      'share_link': 'Compartir',
      'enter_6_digit_code': 'Por favor ingresa un código de 6 dígitos',
      'disable_2fa_question': '¿Desactivar 2FA?',
      'account_less_secure': 'Tu cuenta será menos segura.',
      'recovery_codes': 'Códigos de recuperación',
      'codes_copied': 'Códigos copiados',
      'copy_all': 'Copiar todo',
      'saved_codes': 'He guardado los códigos',
      'two_factor_auth': 'Autenticación de dos factores',
      'secret_copied': 'Secreto copiado',
      'open_in_authenticator': 'Abrir en autenticador',
      'enable_2fa': 'Activar 2FA',
      'disable_2fa': 'Desactivar 2FA',
      'select_date': 'Por favor selecciona una fecha',
      'event_created': 'Evento creado',
      'logout_question': 'Cerrar sesión',
      'logout_confirm': '¿Realmente quieres cerrar sesión?',
      'remove_from_friends': 'Eliminar de amigos',
      'remove_friend_confirm':
          '¿Realmente quieres eliminar a esta persona de tus amigos?',
      'remove': 'Eliminar',
      'add_friend': 'Añadir amigo',
      'friend_request_sent': 'Solicitud enviada',
      'friend_request_received': 'Solicitud de amistad recibida',
      'message': 'Mensaje',
      'friends': 'Amigos',
      'discussions': 'Discusiones',
      'publications': 'Publicaciones',
      'team': 'Equipo',
      'parameters': 'Configuración',
      'no_events': 'No hay eventos',
      'no_groups': 'No hay grupos',
      'no_pages': 'No hay páginas',
      'delete_event': 'Eliminar evento',
      'delete_event_confirm': '¿Realmente quieres eliminar este evento?',
      'event_deleted': 'Evento eliminado',
      'event': 'Evento',
      'month_jan': 'ENE',
      'month_feb': 'FEB',
      'month_mar': 'MAR',
      'month_apr': 'ABR',
      'month_may': 'MAY',
      'month_jun': 'JUN',
      'month_jul': 'JUL',
      'month_aug': 'AGO',
      'month_sep': 'SEP',
      'month_oct': 'OCT',
      'month_nov': 'NOV',
      'month_dec': 'DIC',
      'create': 'Crear',
      'join': 'Unirse',
      'joined': 'Miembro',
      'leave': 'Salir',
      'members': 'miembros',
      'member': 'miembro',
      'group': 'Grupo',
      'page': 'Página',
      'description': 'Descripción',
      'private': 'Privado',
      'public': 'Público',

      // Groups screen
      'error_loading': 'Error',
      'create_group_title': 'Crear un grupo',
      'group_name_label': 'Nombre del grupo *',
      'group_description_label': 'Descripción',
      'group_private_label': 'Grupo privado',
      'group_private_subtitle':
          'Solo los miembros aprobados pueden ver el contenido',
      'group_created_success': '¡Grupo creado!',
      'joined_group': 'Te has unido a',
      'no_groups_message': 'No hay grupos',
      'no_groups_subtitle': '¡Únete o crea un grupo!',
      'discover_groups': 'Descubrir grupos',
      'no_discover_groups': 'No hay grupos para descubrir',
      'all_groups_joined': '¡Eres miembro de todos los grupos!',
      'posts_count': 'publicación',
      'posts_count_plural': 'publicaciones',

      // Pages screen
      'my_pages': 'Mis páginas',
      'followed_pages': 'Seguidas',
      'no_pages_message': 'No hay páginas',
      'create_page_subtitle': '¡Crea una página para tu causa!',
      'create_page_button': 'Crear una página',
      'no_followed_pages': 'No hay páginas seguidas',
      'discover_pages': 'Descubrir páginas',
      'no_discover_pages': 'No hay páginas para descubrir',
      'follow_button': 'Seguir',
      'following_page': 'Sigues a',
      'admin_badge': 'Admin',
      'followers_count': 'seguidor',
      'followers_count_plural': 'seguidores',

      // Group detail screen
      'group_detail_error': 'Error',
      'event_not_found': 'Evento no encontrado',
      'no_posts_yet': 'No hay publicaciones aún',
      'group_settings_title': 'Ajustes del grupo',
      'change_avatar': 'Cambiar avatar',
      'change_cover': 'Cambiar portada',
      'group_name': 'Nombre',
      'group_privacy': 'Privado',
      'view_members': 'Ver miembros',
      'members_title': 'Miembros',
      'organized_by': 'Organizado por',
      'publications_title': 'Publicaciones',

      // Event detail screen
      'event_detail_title': 'Evento',
      'date_and_time': 'Fecha y hora',
      'location': 'Ubicación',
      'participants': 'Participantes',
      'participant_count': 'participante',
      'participant_count_plural': 'participantes',
      'participate_button': 'Participar',
      'participating_status': 'Estás participando ✓',
      'about_event': 'Acerca de este evento',
      'unknown_date': 'Fecha desconocida',
      'monday': 'Lunes',
      'tuesday': 'Martes',
      'wednesday': 'Miércoles',
      'thursday': 'Jueves',
      'friday': 'Viernes',
      'saturday': 'Sábado',
      'sunday': 'Domingo',
      'january': 'enero',
      'february': 'febrero',
      'march': 'marzo',
      'april': 'abril',
      'may': 'mayo',
      'june': 'junio',
      'july': 'julio',
      'august': 'agosto',
      'september': 'septiembre',
      'october': 'octubre',
      'november': 'noviembre',
      'december': 'diciembre',

      // Create event screen
      'create_event_title': 'Crear un evento',
      'event_title_label': 'Título',
      'event_description_label': 'Descripción',
      'event_location_label': 'Ubicación',
      'add_image': 'Añadir una imagen',
      'select_time': 'Seleccionar una hora (opcional)',
      'title_required': 'El título es requerido',
      'date_required': 'Por favor selecciona una fecha',

      // Page detail screen
      'post_added': '¡Publicación añadida!',
      'delete_post_question': '¿Eliminar publicación?',
      'action_irreversible': 'Esta acción es irreversible.',
      'post_deleted': 'Publicación eliminada',
      'edit_post_title': 'Editar publicación',
      'post_content_hint': 'Contenido de la publicación...',
      'post_updated': 'Publicación actualizada',
      'settings_saved': '¡Ajustes guardados!',
      'remove_follower_question': '¿Eliminar este seguidor?',
      'admin_editor_description':
          'Los admins pueden hacer todo. Los editores pueden publicar pero no modificar ajustes.',
      'admin_full_control':
          'Los admins tienen control total sobre la página y los miembros.',
      'editor_limited_access':
          'Los editores pueden publicar pero no gestionar miembros ni ajustes.',
      'private_followers_only': 'Privada - Solo seguidores',
      'no_posts_message': 'No hay publicaciones',
      'no_followers': 'No hay seguidores',
      'no_comments': 'No hay comentarios',
      'subscribed': 'Suscrito',
      'subscribe': 'Suscribirse',
      'follower': 'seguidor',
      'followers_plural': 'seguidores',

      // Create page screen
      'create_page_title': 'Crear una página',
      'create_page_for_cause': 'Crea una página para tu causa',
      'name_field': 'Nombre *',
      'page_name_hint': 'Nombre de la página',
      'category_field': 'Categoría',
      'description_field': 'Descripción',
      'describe_page_hint': 'Describe tu página...',
      'creating': 'Creando...',
      'category_union': 'Sindicato',
      'category_collective': 'Colectivo',
      'category_association': 'Asociación',
      'category_media': 'Medios',
      'category_squat': 'Okupa / Lugar',
      'category_infokiosk': 'Infokiosco',
      'category_artist': 'Artista',
      'category_project': 'Proyecto',
      'category_other': 'Otro',

      // Moderation additional keys
      'mod_already_moderator': '¡Ya eres moderador!',
      'mod_already_candidate': '¡Ya eres candidato!',
      'mod_cancel_candidacy': 'Cancelar mi candidatura',
      'mod_cancel_candidacy_question': '¿Cancelar candidatura?',
      'mod_cancel_candidacy_warning':
          '¿Realmente quieres retirar tu candidatura?\nPerderás todos los votos recibidos.',
      'mod_candidacy_cancelled': 'Candidatura cancelada.',
      'mod_vote_recorded': '¡Voto registrado!',
      'mod_elected_consensus': '¡Moderador elegido por consenso!',
      'mod_revoked_consensus': '¡Moderador revocado por consenso!',
      'mod_post_deleted_action':
          'Publicación eliminada por acción de moderador',
      'mod_no_actions': 'No hay acciones registradas',
      'mod_your_candidacy': 'Esta es tu candidatura',
      'promote_to_admin': 'Promover a Admin',
      'promote_to_admin_question': '¿Promover a {username} a admin?',
      'demote_to_editor': 'Degradar',
      'demote_to_editor_question': '¿Degradar a {username} al rol de editor?',
      'add_member': 'Añadir un miembro',
      'add': 'Añadir',
      'add_media': 'Añadir un medio',
      'add_cover': 'Añadir una portada',
      'page_name': 'Nombre de la página',
      'category': 'Categoría',
      'remove_member': 'Eliminar',
      'remove_member_title': '¿Eliminar este miembro?',
      'remove_follower_title': '¿Eliminar este seguidor?',

      // Search screen
      'search_users_posts': 'Buscar usuarios o publicaciones',
      'no_results': 'Sin resultados',
      'users_tab': 'Usuarios',
      'posts_tab': 'Publicaciones',
      'just_now': 'Ahora mismo',
      'unknown_user': 'usuario',

      // Notifications screen
      'no_notifications': 'No hay notificaciones',
      'notification_like': 'le gustó tu publicación',
      'notification_comment': 'comentó tu publicación',
      'notification_follow': 'comenzó a seguirte',
      'notification_mention': 'te mencionó',
      'notification_reaction': 'reaccionó a tu publicación',
      'notification_message': 'te envió un mensaje',
      'notification_message_request': 'te envió una solicitud de mensaje',
      'notification_friend_request': 'te envió una solicitud de amistad',
      'notification_friend_accept': 'aceptó tu solicitud de amistad',
      'notification_group_invite': 'te invitó a unirte a un grupo',
      'notification_event_invite': 'te invitó a un evento',
      'notification_post_share': 'compartió tu publicación',
      'notification_generic': 'notificación',
      'minutes_short': 'min',
      'hours_short': 'h',
      'days_short': 'd',
      'reply': 'Responder',
      'reply_to': 'Responder a {username}',
      'replies': 'respuestas',
      'reply_count': '{count} respuesta',
      'reply_count_plural': '{count} respuestas',

      // Llamadas (privadas y de grupo)
      'call_audio': 'Llamada de audio',
      'call_video': 'Llamada de video',
      'call_group_audio': 'Llamada de audio grupal',
      'call_group_video': 'Llamada de video grupal',
      'call_connecting': 'Conectando...',
      'call_ringing': 'Llamando...',
      'call_active': 'Conectado',
      'call_ended': 'Llamada terminada',
      'call_rejected': 'Llamada rechazada',
      'call_missed': 'Llamada perdida',
      'call_incoming': 'Llamada entrante',
      'call_answer': 'Responder',
      'call_decline': 'Rechazar',
      'call_end': 'Colgar',
      'call_mute': 'Silenciar',
      'call_unmute': 'Activar micrófono',
      'call_camera_on': 'Cámara activada',
      'call_camera_off': 'Cámara desactivada',
      'call_switch_camera': 'Cambiar cámara',
      'call_participants': 'Participantes',
      'call_participant_count': '{count} participante(s)',
      'call_joining': 'Uniéndose...',
      'call_network_reconnecting': 'Reconectando...',
      'call_you': 'Tú',
      'call_history': 'Historial de llamadas',
      'call_duration': 'Duración',
      'call_incoming_from': 'Llamada entrante de {name}',
      'call_group_incoming': 'Llamada grupal en {group}',

      // Discovery
      'discover_militants': 'Descubrir militantes',
      'discover_militants_desc':
          'Encuentra nuevos militantes y causas para apoyar',
      'new_militants': 'Nuevos militantes',
      'militants_same_cause': 'Militantes de la misma causa',
      'suggested_militants': 'Militantes sugeridos',
      'suggested_groups': 'Grupos sugeridos',
      'suggested_pages': 'Páginas sugeridas',
      'retry': 'Reintentar',
      'subscription_success': 'Suscripción exitosa',
    },
  };

  String translate(String key) {
    final langCode = value.languageCode;
    return _localizedValues[langCode]?[key] ??
        _localizedValues['fr']![key] ??
        key;
  }
}
